### ISSUE TITLE
Ability to choose to store (or not) SessionApp in influx

### ISSUE THREAD

**Issue by TehesFR** [ptarmiganlabs/butler-sos#105]
Hi,

Since Qlik Sense February 2020, several session apps are created when users are working with Qlik Sense, and unfortunately, having them listed in the "in_memory", "loaded", and "active" docs in influxdb can result in something difficult to read when displayed in a grafana dashboard.

It would be really great to have a flag "yes/no" in the config file to choose if we want to store these session apps or not in influx.

Thanks for your work !

**Comment by mountaindude** [comment]
Good idea. I'd like to suggest a twist of this:

**EITHER** 1
- Store data on regular apps (all apps with app names NOT starting with SessionApp_ in one Influx measurement.
- Store data on session apps in a separate measurement.

**OR** 2
- Store all app metrics in a single measurement, but tag session apps with a new tag, similar to how server tags can be specified in the config file.

**OR** 3
- A new flag in the config file controls whether session app data is stored in Influx or not. Just on/off thus.

**OR** 4
- We just drop all session apps all together. I don't particularly fancy this option though.


Do you see any pros/cons with the options?
All should be pretty doable in terms of implementation, with 3 being the easiest, obviously.

**Comment by TehesFR** [comment]
Hi,

I like the option 1 or 2.
It will allow us to keep track of the sessionApps, but also easily choose to display them or not in grafana.

And I feel like the first one would be the best, because it will be well organized in influxdb.

Thanks
