### ISSUE TITLE
Missing committed mem metric

### ISSUE THREAD

**Issue by ot3kcw6c** [ptarmiganlabs/butler-sos#113]
**Describe the bug**
There is a missing metric from the healthcheck api.
https://butler-sos.ptarmiganlabs.com/docs/getting_started/influxdb_data_structure/#measurement-mem
Missing:
committed | integer | The total amount of committed memory for the engine process in MB.

**To Reproduce**
Start butler-sos v5.0.1 or v5.3.0(both tested) and try to select the commited memory in the influxDB.

**Expected behavior**
Selectable metric like allocated and free memory.

**Screenshots**
![image](https://user-images.githubusercontent.com/61137563/83244897-4c969e00-a1a0-11ea-9a42-afe04c0db8f5.png)

**Describe environment:**
 - OS: Ubuntu 18.04
 - Containerisation yes (19.03.6)
 - Version of Butler SOS used v5.0.1 and v5.3.0

**Comment by mountaindude** [comment]
Oooooh nice find. I noticed the same a while back but never got around to investigate it. 
Fixed now in development, I hope to release a 5.4.0 in a few days, with this bug fix (and some new features!) included.
