### ISSUE TITLE
Centralised Logging QS feature decommissioned from May 2021

### ISSUE THREAD

**Issue by deanegan** [ptarmiganlabs/butler-sos#238]
Hello,

I can see that Butler-SOS uses two ways of gathering data from QS which is using Qlik's centralised logging service and using the HealthCheck API. 
The issue with that is Qlik have deprecated the centralised logging service in their more recent versions. I am using May 2021 and when installing it, you never get the option to configure the logging service and you cannot enable it post installation. Here is an article about it: https://community.qlik.com/t5/Support-Updates-Blog/Deprecation-of-Centralized-Logging-in-Qlik-Sense-Enterprise-on/ba-p/1810447#comments

Are there any plans to update Butler SOS to use the standard log/archived log files from the file share?

Kind Regards,
Dean

**Comment by mountaindude** [comment]
I'll take a look at this during coming weeks.

As a starting point I wrote a [community post](https://github.com/ptarmiganlabs/butler-sos/discussions/241), feel free to read it and if possible run the mentioned log db queries. Or just share your wish list for what log events you'd like to see in Butler SOS.

**Comment by mountaindude** [comment]
Cleaning up old tickets - closing.
