### ISSUE TITLE
Cannot find 'fastify'

### ISSUE THREAD

**Issue by BenjaminBGroff** [ptarmiganlabs/butler-sos#251]
I am trying to run butler sos through node but am getting an error 'Error: Cannot find module 'fastify'. I see that you updated the fastify-metrics dependency in version 6.0.2, I just wanted to see if this is an issue that other people are having or if it is something wrong on my end. I was running the version 6.0.1 and once I noticed my issue I updated to version 6.1.2 but error is still persisting.

I also want to note that it had been working for me for a while and this is my first time noticing any issues.

![image](https://user-images.githubusercontent.com/88054931/140989585-c04f76cb-68d1-434d-9e85-696696080b47.png)

Environment:
 - Windows Server 2016
 - Containerisation: no
 - Butler SOS v6.1.2
 - node butler-sos.js

Any help would be greatly appreciated!

**Comment by BenjaminBGroff** [comment]
According to the last time my Grafana dashboard received data the issue occurred on Thursday November 4th around 7:30pm if that helps or changes anything. No changes have been made to Butler on that server until today when the issue was brought to my attention.

**Comment by mountaindude** [comment]
Hi,

Thanks for reporting this,I'll in what ways I can.
Focus last month or two has been on taking the [Butler](https://butler.ptarmiganlabs.com) tool to the next level (including a significant re-write to make things more stable, scalable, future proof, secure etc).

The plan is to do a similar exercise for Butler SOS during coming weeks/month, so good things are coming. 
That won't help you in this case though, of course.

I will do a fresh install of v6.1.2 here to see if I can replicate the problem.
The library "Fastify" that's mentioned in your error is the new framework used to handle various http/web stuff. It's way more modern, supported and in general good than the previously used one, so the change is a good one. But it should work too...

One question: 
I assume this error occurred after an upgrade from some earlier version to v6.1.2?
If that's *not* the case - for example if this occurred spontaneously - it's **very** strange...

**Comment by mountaindude** [comment]
v6.1.2 works fine here, when installed from the [release package](https://github.com/ptarmiganlabs/butler-sos/releases).

But you have to install all dependencies after unzipping the file you downloaded (`butler-sos-butler-sos-v6.1.2.zip`).
This is done by running `npm I` from within the `src` subdirectory.

Something like this:

```bash
➜  butler-sos-butler-sos-v6.1.2 cd src
➜  src npm i
npm WARN deprecated later@1.2.0: Please upgrade to the maintained and new drop-in replacement @breejs/later at https://github.com/breejs/later 🚀 Thanks and happy hacking! 🚀  @niftylettuce

added 324 packages, and audited 325 packages in 2s

54 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  src 
```

Note: The warning about the later library being deprecated is something that will be addressed in next version of Butler SOS, tracked in #252.

**Comment by mountaindude** [comment]
Adding to the above, if I **don't** run `nom I` I get exactly the error you describe.

Sooo... could it be that you forgot to do a `npm I`?
Or that the `src/node_modules` directory has been deleted?

General installation instructions are found at [butler.ptarmiganlabs.com](https://butler-sos.ptarmiganlabs.com/docs/getting_started/install/native/windows/#installation).

**Comment by BenjaminBGroff** [comment]
Hi,

Thank you for helping me out! I am now realizing that my node_modules directory is deleted. I really don't understand how that happened and I was out when it randomly went down lol. Either way I was able to get it back up and working, thank you for your help!

**Comment by mountaindude** [comment]
Good to hear things worked out!
