### ISSUE TITLE
Error in config/default_template.yaml

### ISSUE THREAD

**Issue by gorkor** [ptarmiganlabs/butler-sos#3]
There are two erroneous lines in the mqttConfig part of config/default_template.yaml

is:
    brokerIP: <IP of MQTT server>
    brokerHost: 1883

should be:
    brokerHost: <IP of MQTT server>
    brokerPort: 1883

**Comment by mountaindude** [comment]
Ohh I think you might be right - copy/paste error it seem. Will verify it and fix if needed. 
Thanks!

**Comment by mountaindude** [comment]
Fixed in latest commit.
