### ISSUE TITLE
variable mismatch

### ISSUE THREAD

**Issue by gorkor** [ptarmiganlabs/butler-sos#5]
variable e and err mismatch:
https://github.com/ptarmiganlabs/butler-sos/blob/master/butler-sos.js#L385-L388

**Comment by mountaindude** [comment]
Thanks for the bug report, it indeed looks like a typo.

It is fixed as of (this commit)[https://github.com/ptarmiganlabs/butler-sos/commit/315f9dad7690150bea72adcfb93ccda685d2d067]
