### ISSUE TITLE
Show App names in addition to app ids

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#67]
Right now the IDs of all loaded/active apps are extracted from Sense and stored in InfluxDB. That's fine, but it would also be useful to have the actual app names in InfluxDB (and Grafana of course).

**Comment by mountaindude** [comment]
I have started to implement this feature, but I am not sure how app names are best visualised in Grafana - and thus not sure how to best store them in Influxdb.

A basic first solution (and the one I am currently implementing) would be to just create a comma separated list of the names of all loaded/active apps, and store that list in Influxdb together with the other health metrics. 

Another option would be to store the app names as tags in Influxdb, but that would serve little purpose as no health metrics are available on a per-app basis (i.e. only aggregated metrics are available).

Any thoughts from others here?

**Comment by TehesFR** [comment]
Hi there, 

In my opinion, I would definitely go for a sorted, comma separated list of the names.
Nothing more is needed I guess :)

**Comment by mountaindude** [comment]
Cool, let's stick with that plan then.

Regarding sorting:

It does make sense to have the app list alfa sorted, of course. 
But it also makes sense to have the list of active/loaded/in-memory app IDs appear in the same order as the app names list... I'll probably do things that way. Which means the order of app IDs will be different from how they are retrieved from the Sense API, but I can't see that being a problem.

**Comment by mountaindude** [comment]
Added in version 5.2.0.
https://github.com/ptarmiganlabs/butler-sos/releases/tag/v5.2.0

@TehesFR Feel free to check it out!
