### ISSUE TITLE
[docker] mountaindude/butler-sos:5.0.0 not found

### ISSUE THREAD

**Issue by TehesFR** [ptarmiganlabs/butler-sos#72]
Hi there,

First of all, this is a great tool, thank you for sharing !

Just for you to know, currently there is no 5.0.0 tag available on your docker image as stated in the doc, only tags 5.0.0RC1 and 5.0.0RC2.

Thanks

Best regards,

**Comment by TehesFR** [comment]
SORRY my bad, it's now ptarmiganlabs/butler-sos

Thanks!

**Comment by mountaindude** [comment]
Ok good that you found it.

I check just now, and
https://butler-sos.ptarmiganlabs.com/docs/getting_started/choose_platform/ does
link to the correct Docker Hub page.

/Göran
