### ISSUE TITLE
Mosquitto installation

### ISSUE THREAD

**Issue by ABMerr** [ptarmiganlabs/butler-sos#8]
Has anyone tried install the Mosquitto? I couldn't manage to get it install keeps saying cannot complete please reinstall.. Does butler have to run with a MQTT application? Any other choice?

**Comment by mountaindude** [comment]
What operating system did this happen on?
Installing MQTT has always been 100% smooth for me, on Mac OS and Linux at least. Never tried it on Windows.

You can disable MQTT in Butler SOS by setting the "enableMQTT" parameter in the config file to false.

**Comment by ABMerr** [comment]
Thank you mate! I am installing on Windows unfortunately.. Maybe I should try on Linux..
Another silly question.. Without MQTT, what functionality do I loose when using butler?

**Comment by mountaindude** [comment]
MQTT is a machine-to-machine protocol, often used in Internet of Things applications. Such as sending a sensor reading from one computer to a server.

Butler SOS uses MQTT as the transport layer for sending the Sense related measurements it collects   to other systems. 
For example, Node RED can be used to visually prototype new applications that use the metrics coming from Sense (via Butler SOS) - thanks to both Butler SOS and Node RED talking MQTT.

If you don't have any plans to send the sensor data to other systems, you can safely start off with MQTT disabled.

**Comment by ABMerr** [comment]
That's very clear. I will give it a try and see how it goes. Thanks a lot!!
